## 0.4: New note diagram

```mermaid
sequenceDiagram
participant browser
participant server

    browser->>server: POST https://studies.cs.helsinki.fi//exampleapp/new_note
    activate server
    	Note right of browser: Click save note button


    server-->>browser: HTTP Server Response 302
    deactivate server
    Note right of browser: Server requests the browser to make a new HTTP GET request to the address .../exampleapp/notes

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/notes
    activate server
    Note right of browser: The browser request the notes page
    server-->>browser: HTML document
    deactivate server

    Note right of browser: The browser reloads the notes page and request the other necessary files (main.css, main.js, data.json)
```
